### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [b1scoito/mpv-cut#5]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by b1scoito** [comment]
Made a PR to them.

**Comment by z8512** [comment]
Thank you very much
