### ISSUE TITLE
Issues after cutting

### ISSUE THREAD

**Issue by ma-zsola** [b1scoito/mpv-cut#6]
Thank you for the script.
I use the script with the original settings without re-encoding, with the latest mpv on Windows 11. I cut only local mp4 files with it. 

1. When the first cutting mark is not a keyframe the mpv shows a negative starting position (elapsed time).
![kép](https://user-images.githubusercontent.com/106858326/176998246-bb44e30f-c29b-46bb-a9f5-5ab5f3e2768d.png)
2. When the first cutting mark is not a keyframe the video always freezes at the cutting mark for a few seconds. After it, the audio desync like mentioned in #3 .
3. When I open the cutted file which I have never opened before, it starts from a random position, not from the beginning. In these cases the mvp seekbar doesn't work properly. It doesn't accept the selected seeking position.

 Is there a way to prevent these issues?

**Comment by b1scoito** [comment]
Hey, this is known issue with FFmpeg itself and apparently it's not fixable without re-encoding, I really tried everything, every way possible to sync the audio with the video and got no results out of it. What I'd recommend is removing de codec copy argument directly on the script, it'll take longer to cut a video but will stop this from happening.

**Comment by ma-zsola** [comment]
Thank you for your feedback. 
After removing the codec copy argument, it works fine.
